---
apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    greeting: personalized
spec:
  containers:
    - name: hello
      image: ubuntu:18.04
      env:
        - name: "NAME"
          value: "Matt"
      command: ['sh', '-c', 'echo "Hello, ${NAME}" && sleep 3600']