---
apiVersion: v1
kind: Service
metadata:
  name: jmmason-test-redis-service
  labels:
    username: jmmason
    env: test
spec:
  type: ClusterIP
  selector:
    username: jmmason
    env: test
    app: jmmason-test-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379