---
apiVersion: v1
kind: Service
metadata:
  name: jmmason-test-flask-service
  labels:
    username: jmmason
    env: test
spec:
  type: ClusterIP
  selector:
    username: jmmason
    env: test
    app: jmmason-test-flask
  ports:
  - name: flask
    port: 5000
    targetPort: 5018