---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmmason-test-flask-deployment
  labels:
    app: jmmason-test-flask
    username: jmmason
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jmmason-test-flask
  template:
    metadata:
      labels:
        app: jmmason-test-flask
        username: jmmason
        env: test
    spec:
      containers:
        - name: jmmason-test-flask
          imagePullPolicy: Always
          image: johnmmason/coe-332-animals:1.0
          ports:
            - name: flask
              containerPort: 5000
          env:
            - name: "REDIS_HOST"
              value: "10.102.45.189"