version: '3'

services:

  redis:
    container_name: jmm-redis
    image: redis:latest
    ports:
      - 6398:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

  web:
    build: web
    ports:
      - "5018:5000"