---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmmason-hw7-redis-pvc
  labels:
    username: jmmason
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi