---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmmason-hw7-redis-deployment
  labels:
    app: jmmason-hw7-redis
    username: jmmason
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmmason-hw7-redis
  template:
    metadata:
      labels:
        app: jmmason-hw7-redis
        username: jmmason
        env: test
    spec:
      containers:
        - name: jmmason-hw7-redis
          image: redis:5.0.0
          volumeMounts:
          - name: jmmason-hw7-redis-pvc
            mountPath: "/data"
          ports:
            - name: redis
              containerPort: 6379
      volumes:
      - name: jmmason-hw7-redis-pvc
        persistentVolumeClaim:
          claimName: jmmason-hw7-redis-pvc